### ASSIGNMENT 1 

**NAME:** Chan Jun Yao

**MATRIC:** A18CS0043

**Topic: Data Structure, Functions and Files in Python**
- Due: 1 week from announcement.
- Mode: Individual
- Submission: E-Learning

Given a data file that consists of an example daily sale information recorded manually for each of the transaction for a certain period. The information in the file consists of date, item name, amount sold, and price per unit.

<br>
<img src='Fig1.png' width='300px'>
The sample of the data

**INSTRUCTIONS:**
1. Reads the data file in Python.
2. Creates a function in Python called: **calculate_daily_sale** that:
   - Able to calculate and return the sale of each item for every day.
   - You need to determine the data structure for the returned information, where the returned result should be able to be accessed to show the sale of exact item on a specified day. E.g.: 
      - ```result[“2020-09-25”]``` *will returns the sale for each item on that day.*
      - ```result[“2020-09-25”][“Item_B”]``` *will returns the sale of Item B on that day.*
3. Creates a function in Python called: **get_total_sale** that:
   - Able to combine the sale of a specific item throughout the period in the data file.
   - The function should receive ONE argument:
     - The result variable returned form **calculate_daily_sale**
   - The function should return the total sale of each item throughout the period.
4. Submit your Python Notebook in the E-Learning.

In [1]:


def read_sales_data(filename):
    
    result = {}
    
    with open(filename) as dataFile:
        lines = [line.rstrip() for line in dataFile]
    
    for index,line in enumerate(lines):
        [date,item,amount,price] = line.split(" ")
                        
        if date in result:
            if item in result[date]:
                result[date][item] = int(result[date][item]) + (int(amount) * float(price))
            else:
                result[date][item] = (int(amount) * float(price))
        else:
            result[date] = {
                item: (int(amount) * float(price))
            }
            
    return result
    
def calculate_daily_sale(data):
    
    dailySaleData = {}
    
    for key,day in enumerate(data):
        dailyTotal = 0
        for item in data[day]:
            dailyTotal = dailyTotal + int(data[day][item])
        dailySaleData[day] = dailyTotal
    
    return dailySaleData

def get_total_sale(data):
    daySale = calculate_daily_sale(data)
    total = 0
    for key,sale in enumerate(daySale):
        total = int(total) + daySale[sale]
    return total

def display_df(result,dailySales):
    resultDf = pd.DataFrame(list(result.items()),columns = ['Date','item_sale'])
    resultDf = pd.concat([resultDf.item_sale.apply(pd.Series), resultDf.drop('item_sale', axis=1)], axis=1)
    dsDF = pd.DataFrame(list(dailySales.items()),columns = ['Date','Daily Sales'])
    df = pd.concat([dsDF,resultDf.drop('Date',axis=1)],axis=1)
    display(df)

In [2]:
import pandas as pd

result = read_sales_data('data_assignment_1.txt')
dailySales = calculate_daily_sale(result)
totalSales = get_total_sale(result)

display_df(result,dailySales)



print('Total sales: ' + str(totalSales))

# VERFIY

print('\nValidate: print the given syntax in the question.\n')

print(result['2020-09-25'])
print(result['2020-09-25']['Item_B'])

         Date  Daily Sales  Item_A  Item_B  Item_C  Item_D  Item_E  Item_F
0  2020-09-23           22    12.8    10.6     NaN     NaN     NaN     NaN
1  2020-09-24           36    24.7     2.4    10.4     NaN     NaN     NaN
2  2020-09-25           71    28.5     7.2     NaN    36.9     NaN     NaN
3  2020-09-26           64    16.6    38.4    10.4     NaN     NaN     NaN
4  2020-09-27           65     3.8     3.6    15.6    40.5     4.4     NaN
5  2020-09-28          103    31.5     7.2    14.3    29.7     4.4    18.4
6  2020-09-29           44    27.5    17.2     NaN     NaN     NaN     NaN
7  2020-09-30          102    11.4     7.2    30.7    44.9     4.4     6.4

Total sales: 507

Validate: print the given syntax in the question.

{'Item_D': 36.900000000000006, 'Item_A': 28.5, 'Item_B': 7.199999999999999}
7.199999999999999